name: To-deploy
on: push
jobs:
    ubuntu_start:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install dep
              run: |
                npm install -g bats
                bats -v
                echo 'Install final'
            - name: Step_Test2
              run: echo 'Test 2 good'
